baseURL = "/"
defaultContentLanguage = "id"
languageCode = "id-ID"
staticDir = "static"
title = "Blogfolio Najib"
# defaultContentLanguageInSubdir = true
background = "images/topography.svg"
canonifyURLs = true
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
enableRobotsTXT = true
feature_image = "images/topography.svg"
theme = "hugo-casper3"

enableGitInfo = true

[languages]
[languages.id]
languageCode = "id-ID"
languageName = "Bahasa Indonesia"
weight = 1
[languages.en]
languageCode = "en-US"
languageName = "English"
weight = 2

[markup]
defaultMarkdownHandler = "goldmark"

[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2

[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
wrapStandAloneImageWithinParagraph = false
[markup.goldmark.parser.attribute]
block = true
title = true
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ""
hl_inline = false
lineAnchors = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = "modus-vivendi"
tabWidth = 4

# [taxonomies]
#   tag = "tags"

[params]
background = "images/topography.svg"
facebook = "fanajib5"
github = "fanajib5"
images = ["apple-touch-icon.png"]
twitter = "fanajib5"

[[params.author]]
name = "Faiq Najib"

[menu]

[[menu.main]]
name = "Post"
pageref = "/post"
weight = 10
[menu.main.params]
description = "Arsip artikel"

[[menu.main]]
name = "Gallery"
pageref = "/gallery"
weight = 20
[menu.main.params]
description = "Album foto"

[[menu.main]]
name = "Link"
pageref = "/link"
weight = 30
[menu.main.params]
description = "Tautan dan papan pesan"

[[menu.main]]
name = "About"
pageref = "/about"
weight = 40
[menu.main.params]
description = "Tentang"
